######################## default configuration ####################
baseURL = "https://binnariumedu.com"
title = "Binnarium"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
defaultContentLanguage = "es"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Binnarium"
weight = 1
hasChildren = true

  [[menu.main]]
  parent = "Binnarium"
  name = "Somos Binnarium"
  URL = "about"

  [[menu.main]]
  parent = "Binnarium"
  name = "Equipo"
  URL = "employee"

#  [[menu.main]]
#  parent = "Binnarium"
#  name = "Trabajos"
#  URL = "scholarship"

[[menu.main]]
name = "¿Qué hacemos?"
URL = "portfolio"
weight = 2

[[menu.main]]
name = "Mundo Binnarium"
URL = "blog"
weight = 4
  
[[menu.main]]
name = "Contáctanos"
URL = "contact"
weight = 5

#################### default parameters ################################
[params]
logo = "images/binnarium-logo-white.svg"
# Meta data
description = "Generando Innovación en el modelo de enseñanza aprendizaje"
author = "Binnarium"
# contact info
address = "San Cayetano Alto, Calle París, Loja"
mobile = "+593 98 730 7747"
email = "serviciocliente@Binnarium.io"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = ""
# top header
top_header = false

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=es"
map_latitude = "-3.9869567"
map_longitude = "-79.1993367"
map_marker = "images/marker.png"
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"


################################### Spanish language #####################################
[Languages.es]
languageName = "Español"
languageCode = "es-ES"
contentDir = "content/spanish"
weight = 1
home = "Inicio"
# copyright
copyright = "Derechos de Autor &copy; 2020 Binnarium"

#################################### English language #####################################
# [Languages.en]
# languageName = " English"
# languageCode = "en-us"
# contentDir = "content/english"
# weight = 2
# home = "Home"
# # copyright
# copyright = "Copyright &copy; 2020 Binnarium"


