---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Inicio
- type: document
  path: data/es/homepage.md
  label: P치gina de Inicio
- type: heading
  label: Portafolio
- type: document
  path: content/spanish/portfolio/_index.md
  label: P치gina de inicio
- type: directory
  path: content/spanish/portfolio
  label: Proyectos
  create: documents
  match: "**/*"
  exclude: _index*
  templates:
  - portafolio
- type: heading
  label: Mundo Binarium
- type: document
  path: content/spanish/blog/_index.md
  label: Inicio
- type: directory
  path: content/spanish/blog
  label: Publicaciones
  create: all
  match: "**/*"
  exclude: _index*
  templates:
  - blog
- type: heading
  label: Sobre Nosotros
- type: document
  path: content/spanish/about/_index.md
  label: Sobre Nosotros
- type: document
  path: data/es/about.md
  label: Datos Sobre Nosotros
- type: heading
  label: Contacto
- type: document
  path: content/spanish/contact/_index.md
  label: Contacto
- type: heading
  label: Equipo
- type: document
  path: content/spanish/employee/_index.md
  label: Inicio
- type: directory
  path: content/spanish/employee
  label: Equipo
  create: all
  match: "**/*"
  exclude: _index*
  templates:
  - team-member
- type: heading
  label: Configuraci칩n
- type: directory
  path: ''
  label: Configuraci칩n del Sitio
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.71.1
