---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Blog
- type: directory
  path: content/english/blog
  label: English
  create: all
  match: "**/*"
- type: directory
  path: content/spanish/blog
  label: Español
  create: all
  match: "**/*"
- type: heading
  label: Portafolio
- type: document
  path: content/spanish/portfolio/_index.md
  label: Español / Inicio
- type: document
  path: content/english/portfolio/_index.md
  label: Ingles / Proyectos
  match: "**/*"
- type: directory
  path: content/portfolio
  label: Portfolio Projects
  create: documents
  match: "**/*"
  exclude: _index*
  templates:
  - project-template
- type: heading
  label: Data
- type: document
  path: data/homepage.yml
  label: Homepage
- type: document
  path: data/about.yml
  label: About
- type: heading
  label: Content
- type: document
  path: content/about/_index.md
  label: About
- type: document
  path: content/contact/_index.md
  label: Contact
- type: heading
  label: Configuration
- type: directory
  path: ''
  label: Site Config
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.71.1
